name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  push_docker_image:
    name: Build & Publish Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Create SHA Container Tag
        id: sha_tag
        run: |
          tag=$(cut -c 1-7 <<< $GITHUB_SHA)
          echo "::set-output name=tag::$tag"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN  }}

      # This step builds and pushed the container to the
      # Github Container Registry tagged with "latest" and
      # the short SHA of the commit.
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          cache-from: type=registry,ref=ghcr.io/python-discord/ledger:latest
          tags: |
            ghcr.io/python-discord/ledger:latest
            ghcr.io/python-discord/ledger:${{ steps.sha_tag.outputs.tag }}

#      - name: Authenticate with Kubernetes
#        uses: azure/k8s-set-context@v1
#        with:
#          method: kubeconfig
#          kubeconfig: ${{ secrets.KUBECONFIG }}
#
#      - name: Deploy to Kubernetes
#        uses: Azure/k8s-deploy@v1
#        with:
#          manifests: |
#              deployment.yaml
#          images: 'ghcr.io/python-discord/metricity:${{ steps.sha_tag.outputs.tag }}'
#          kubectl-version: 'latest'
