name: Lint Python code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: "Lint code"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Install Poetry and project dependencies
      uses: knowsuchagency/poetry-install@v2

    - name: Setup flake8 annotations
      uses: rbialon/flake8-annotations@v1

    - name: Lint code with Flake8
      run: poetry run flake8 . --count --show-source --statistics

